# Generated by Django 5.0 on 2025-12-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, help_text="Your professional title, e.g., 'Full Stack Developer'", max_length=100, verbose_name='title'),
        ),
    ]
