# Generated by Django 5.0 - Database Performance Optimization
"""
Migration to add database indexes for improved query performance.

This migration adds indexes on frequently queried fields to optimize:
- Dashboard queries (user + status combinations)
- Featured content filtering
- Date-based sorting and filtering
- Full-text search preparations
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add performance indexes to portfolio models."""

    dependencies = [
        ("portfolio", "0003_activitylog_githubimport_saveddraft"),
    ]

    operations = [
        # Project indexes for common query patterns
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "status"],
                name="port_proj_user_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "is_featured"],
                name="port_proj_user_feat_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["-created_at"],
                name="port_proj_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["slug"],
                name="port_proj_slug_idx",
            ),
        ),
        # Skill indexes
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["user", "category"],
                name="port_skill_user_cat_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["-proficiency"],
                name="port_skill_prof_idx",
            ),
        ),
        # Experience indexes for timeline queries
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["user", "-start_date"],
                name="port_exp_user_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["user", "is_current"],
                name="port_exp_user_current_idx",
            ),
        ),
        # Education indexes
        migrations.AddIndex(
            model_name="education",
            index=models.Index(
                fields=["user", "-start_date"],
                name="port_edu_user_date_idx",
            ),
        ),
        # Certification indexes
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(
                fields=["user", "-issue_date"],
                name="port_cert_user_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(
                fields=["user", "expiry_date"],
                name="port_cert_user_expiry_idx",
            ),
        ),
        # ContactMessage indexes for inbox queries
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["recipient", "status"],
                name="port_msg_user_read_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["recipient", "-created_at"],
                name="port_msg_user_date_idx",
            ),
        ),
        # Analytics indexes for reporting
        migrations.AddIndex(
            model_name="profileview",
            index=models.Index(
                fields=["user", "viewed_at"],
                name="port_pview_user_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectview",
            index=models.Index(
                fields=["project", "viewed_at"],
                name="port_projview_date_idx",
            ),
        ),
        # ActivityLog indexes for audit trail
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "-created_at"],
                name="port_actlog_user_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["action", "-created_at"],
                name="port_actlog_type_time_idx",
            ),
        ),
        # SocialLink indexes
        migrations.AddIndex(
            model_name="sociallink",
            index=models.Index(
                fields=["user", "platform"],
                name="port_social_user_plat_idx",
            ),
        ),
    ]
